### PR TITLE
emails now have mailto link

### PR DESCRIPTION
**Pull request by Adman**
* this fixes [#78](https://github.com/fmfi-svt/votr/issues/78)

Signed-off-by: Adrian Matejov <a.matejov@centrum.sk>

[Review on Reviewable](https://reviewable.io/reviews/fmfi-svt/votr/95)

### CODE REVIEW

**Comment by Adman** [comment]
cc @TomiBelan

**Comment by Adman** [comment]
cc @AnotherKamila

**Comment by TomiBelan** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fmfi-svt/votr/95)*

**Comment by TomiBelan** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[a discussion](https://reviewable.io:443/reviews/fmfi-svt/votr/95#-KESedm3Vz9u8ndqQ3SH:-KESdjxJ7WbxucrVzbyd:1047711647) (no related file):*
Vdaka za kod, a pardon za zdrzanie!
Len jeden detail: ak je email prazdny, toto vyrobi <a href="mailto:">. Mozno by bolo lepsie nevyrobit vtedy ziaden <a>. Takze asi treba nieco ako `<td>{osoba.email && <a...>...</a>}</td>`.
Okrem tohto LGTM.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fmfi-svt/votr/95)*

**Comment by TomiBelan** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/fmfi-svt/votr/95#-KESedm3Vz9u8ndqQ3SH:-KESf-sNNXz-dxrF5Mpd:49097293) (no related file):*
Gah, zle formatovanie. Chcel som povedat ze ked je email `""` tak toto vyrobi `<a href="mailto:">` a ze by bolo lepsie nevyrobit ziaden `<a>`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fmfi-svt/votr/95)*

**Comment by Adman** [comment]
@TomiBelan fixol som to , ale neviem to poriadne otestovat kedze tam nemam studenta bez emailu.

Ak s tym je nejaky problem, treba dat vediet.

**Comment by Adman** [comment]
cc @Sameth

**Comment by Adman** [comment]
@TomiBelan @Sameth @AnotherKamila Anyone?

**Comment by Adman** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/fmfi-svt/votr/95#-KESedm3Vz9u8ndqQ3SH:-KQtaTyJUA6_vvYMAdR8:b-1g6kcn) (no related file):*
<details><summary><i>Previously, TomiBelan (Tomi Belan) wrote…</i></summary>
> Gah, zle formatovanie. Chcel som povedat ze ked je email `""` tak toto vyrobi `<a href="mailto:">` a ze by bolo lepsie nevyrobit ziaden `<a>`.
</details>
Malo by to byt spravene.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fmfi-svt/votr/95)*

**Comment by TomiBelan** [comment]
Hanba mi! Hrozne sa ospravedlnujem ze som tak dlho neodpovedal. Dufam ze som ta este celkom neodradil od vyvoja votru, napriek zlej prvej skusenosti...

Naozaj tento kod funguje? Tipujem ze `if (student.email) ...` sa bude interpretovat ako text a doslova sa zobrazi vo vygenerovanom HTML. (Ci uz student ma email alebo nie.) Vid: https://facebook.github.io/react/tips/if-else-in-JSX.html

Takze myslim ze treba nieco taketo: `<td>{student.email ? <a href={...}>{...}</a> : null}</td>`
Alebo ekvivalentne `<td>{student.email && <a href={...}>{...}</a>}</td>`

Co sa tyka testovania: ak mas lokalne rozbehany votr, vo `fladgejt/webui/osoby.py` a `fladgejt/webui/predmety.py` mozes zmenit `email=row['email']` na `email=""` cim kazdy riadok dostane prazdny email.

Kazdopadne, nech uz nemusis dlhsie cakat (este raz pardon...) zajtra sa na to pozriem a ak treba tak vyriesim, nech je konecne hotovo.

**Comment by Adman** [comment]
@TomiBelan ok malo by to byt fixnute. Sorry, s nodejs som este nerobil, tak pomaly sa s nim spoznavam. :)

**Comment by TomiBelan** [comment]
Super, otestoval som to a vyzera to dobre. Mergnute a deploynute na votr.uniba.sk. Dakujem za fix.

Mimochodom node.js az tak nepouzivame (iba ako build tool), henta specialna syntax je z React.js. Je to celkom pekna kniznica, odporucam si ju popozerat (ci uz kvoli votr-u alebo vseobecne). https://facebook.github.io/react/index.html

**Pull request merged**
