### PR TITLE
Virpo/ovce popup

### PR DESCRIPTION
**Pull request by ViRPo**
Dirty and brave pull request with marketing popup for anketa.fmph.uniba.sk

---
This change is [Reviewable](https://reviewable.io/reviews/fmfi-svt/votr/105)

### CODE REVIEW

**Comment by mrshu** [comment]
Well, since I took part of the development process, I saw all of this before and it looks good enough for me (with enough being the key part of the sentence).

As most of these changes are temporary, let's get them removed once the campaign is over.

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[votrfront/front.py, line 40 at r3](https://reviewable.io:443/reviews/fmfi-svt/votr/105#-Kl5si3iRvhOsSMVwLlS:-Kl5si3kn_fXpDChB9qr:b-vogkq) ([raw file](https://github.com/fmfi-svt/votr/blob/131006a780e7187e9785ea76f391e248e3dcb293/votrfront/front.py#L40)):*
> ```Python
> <script>Votr = %(init_json)s</script>
> %(scripts)s
> <script type="text/javascript" id="cookiebanner"
> ```

This should have been removed long ago.

Thanks for doing this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fmfi-svt/votr/105#-:-Kl5tCk1_9E3ujluL7vf:b-ec9ka7)*

**Comment by mrshu** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fmfi-svt/votr/105#-:-Kl5un8nrkLaaP8BPCQe:bnfp4nl)*

**Comment by TomiBelan** [comment]
Už sa dá vyhodiť?

**Comment by ViRPo** [comment]
@TomiBelan kedze hlasovanie v ankete skoncilo, tak ano
kedze v tomto PR sa okrem pridavania noveho popupu mazal stary navrhujem, ze zajtra spravim novy PR kde odstranim komplet vsetko

**Comment by TomiBelan** [comment]
Znie ok, dakujem :-)
A kudos ze kod sa sam vypne v urcity datum (ak tomu spravne rozumiem).

**Pull request merged**
